### PR TITLE
Adding SSH keys to install script

### PR DESCRIPTION
**Pull request by archielee**
@TheDash

### CODE REVIEW

**Comment by TheDash** [comment]
The code looks good; can you create a new script/bash file that does this, and then call this seperately from the installation script? The reason being; perhaps the user/ or myself needs to debug ssh setup without having to re-install the package. Or if they want to setup their keys again without re-installing the package. So they can just call the script, instead of re-installation.

**Comment by archielee** [comment]
Ok, will make new commit

**Comment by TheDash** [comment]
Thank you.

**Comment by archielee** [comment]
@TheDash split into different file

**Comment by TheDash** [comment]
Excellent, 
thank you.

**Pull request merged**
